### PR TITLE
Added support for Redux stores

### PR DESCRIPTION
**Pull request by teameh**
See https://github.com/Limenius/ReactBundle/issues/1

### CODE REVIEW

**Comment by teameh** [comment]
Will fix tests in a minute :)

**Comment by teameh** [comment]
I 'squased' the fixes for tests in the last commit

**Comment by teameh** [comment]
Additionally you could consider this commit for better readability. But that's a personal thing ;) 
https://github.com/tiemevanveen/ReactBundle/commit/902012872d6486124a7f5cb8c668468878c79657

**Comment by nacmartin** [comment]
Awesome, thanks! Let me check this with an example that uses this feature before merging. Also, the additional commit looks good too, if you want to add it to the PR.

**Comment by teameh** [comment]
Cool :). Added the commit.

**Comment by teameh** [comment]
Something to watch: https://github.com/shakacode/react_on_rails/issues/309

**Comment by nacmartin** [comment]
Update: I am working on the example with Redux. I got the example of the sandbox working (without using this tag, still), then I will try it server-side, that should work out the box, and then I will play with this tag. Maybe rendering a main component and then a breadcrumb that gets updated from changes in the same store.

**Comment by teameh** [comment]
sounds good!

**Comment by teameh** [comment]
Resolved conflicts with a rebase

**Comment by nacmartin** [comment]
Very nice! I also liked that you don't have to explicitly say that you wanted to render the store server, side in the twig tag of the store, and it gets rendered in the components if needed. :+1:

**Comment by nacmartin** [comment]
Now time for some cleanup of the example and will also update the docs to cover this. It is funny that we will likely have at the end a more complete example of how to use this feature than the React on Rails project :D

**Comment by teameh** [comment]
Awesome!

> Very nice! I also liked that you don't have to explicitly say that you wanted to render the store server, side in the twig tag of the store, and it gets rendered in the components if needed. :+1:

Yeah, me too, that is neat :) 

I haven't used the example yet as I'm using only some classes of the bundle in my Silex project but I could work some on the docs this weekend if you like.

**Pull request merged**
